# Generated by Django 5.2.3 on 2025-06-28 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('used', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_used', models.DateTimeField(blank=True, null=True)),
                ('current_use', models.CharField(blank=True, max_length=255, null=True)),
                ('userGame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to='games.usergame')),
            ],
        ),
    ]
