# Generated by Django 5.2.3 on 2026-02-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0002_share_key_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='share_key_token',
            name='background_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='share_key_token',
            name='donor_username',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='share_key_token',
            name='game_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='share_key_token',
            name='header_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='share_key_token',
            name='publisher',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='share_key_token',
            name='steamapp_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
