# Generated by Django 5.2.3 on 2025-11-15 00:00
from django.db import migrations, models


def copy_game_fields(apps, schema_editor):
    UserGame = apps.get_model('games', 'UserGame')

    # Use iterator to avoid loading entire queryset into memory
    for user_game in UserGame.objects.select_related('game').all().iterator():
        if user_game.game_id:
            game = user_game.game
            if game:
                user_game.name = game.name
                user_game.steamapp_id = game.steamapp_id
                user_game.save(update_fields=['name', 'steamapp_id'])
                continue
        # Fallback in case of missing related Game rows
        if not user_game.name:
            user_game.name = 'Unknown game'
            user_game.save(update_fields=['name'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_rename_steamappid'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergame',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usergame',
            name='steamapp_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RunPython(copy_game_fields, reverse_code=noop),
        migrations.AlterUniqueTogether(
            name='usergame',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='usergame',
            name='game',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.AddConstraint(
            model_name='usergame',
            constraint=models.UniqueConstraint(
                condition=models.Q(steamapp_id__isnull=False),
                fields=('user', 'steamapp_id'),
                name='unique_user_steamapp',
            ),
        ),
    ]
