# Generated by Django 5.2.3 on 2026-02-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0003_share_key_token_display_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='share_key_token',
            name='message_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
